const mongoose = require("mongoose");
require("dotenv").config();

const Product = require("./models/Product");

const products = [
  {
    name: "Puma Deviate NITRO 3",
    category: "Running",
    price: 14999,
    discount: 15,
    rating: 4.9,
  },
  {
    name: "Puma Velocity NITRO 3",
    category: "Running",
    price: 11999,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma ForeverRun NITRO",
    category: "Running",
    price: 13999,
    discount: 10,
    rating: 4.8,
  },
  {
    name: "Puma Electrify NITRO 4",
    category: "Running",
    price: 8999,
    discount: 25,
    rating: 4.7,
  },
  {
    name: "Puma Fast-R NITRO Elite",
    category: "Running",
    price: 16999,
    discount: 5,
    rating: 4.9,
  },
  {
    name: "Puma Magnify NITRO 2",
    category: "Running",
    price: 10999,
    discount: 18,
    rating: 4.7,
  },
  {
    name: "Puma Softride Enzo Evo",
    category: "Running",
    price: 5999,
    discount: 35,
    rating: 4.5,
  },
  {
    name: "Puma Softride Rift",
    category: "Running",
    price: 5499,
    discount: 30,
    rating: 4.4,
  },
  {
    name: "Puma Flyer Runner",
    category: "Running",
    price: 3999,
    discount: 40,
    rating: 4.3,
  },
  {
    name: "Puma Resolve Modern",
    category: "Running",
    price: 4999,
    discount: 28,
    rating: 4.4,
  },
  {
    name: "Puma Twitch Runner",
    category: "Running",
    price: 6499,
    discount: 25,
    rating: 4.5,
  },
  {
    name: "Puma FlexFocus Lite",
    category: "Running",
    price: 3499,
    discount: 45,
    rating: 4.2,
  },
  {
    name: "Puma RS-X Efekt",
    category: "Sneakers",
    price: 10999,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma RS-X Triple",
    category: "Sneakers",
    price: 9999,
    discount: 15,
    rating: 4.7,
  },
  {
    name: "Puma Palermo Leather",
    category: "Sneakers",
    price: 8999,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma Palermo Vintage",
    category: "Sneakers",
    price: 8499,
    discount: 25,
    rating: 4.7,
  },
  {
    name: "Puma CA Pro Classic",
    category: "Sneakers",
    price: 7999,
    discount: 30,
    rating: 4.6,
  },
  {
    name: "Puma CA Pro Lux",
    category: "Sneakers",
    price: 9499,
    discount: 22,
    rating: 4.7,
  },
  {
    name: "Puma Smash 3.0",
    category: "Sneakers",
    price: 4499,
    discount: 40,
    rating: 4.5,
  },
  {
    name: "Puma Smash Vulc",
    category: "Sneakers",
    price: 3999,
    discount: 38,
    rating: 4.4,
  },
  {
    name: "Puma Caven 2.0",
    category: "Sneakers",
    price: 5499,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma Court Classic",
    category: "Sneakers",
    price: 4999,
    discount: 35,
    rating: 4.4,
  },
  {
    name: "Puma Rebound LayUp",
    category: "Sneakers",
    price: 5999,
    discount: 25,
    rating: 4.5,
  },
  {
    name: "Puma Slipstream Lo",
    category: "Sneakers",
    price: 9999,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma Trinity Lite",
    category: "Sneakers",
    price: 6499,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma Fuse 3.0",
    category: "Training",
    price: 8999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma Fuse 2.0",
    category: "Training",
    price: 8299,
    discount: 15,
    rating: 4.7,
  },
  {
    name: "Puma PWRFrame TR 3",
    category: "Training",
    price: 9999,
    discount: 12,
    rating: 4.8,
  },
  {
    name: "Puma Softride Enzo NXT",
    category: "Training",
    price: 6499,
    discount: 25,
    rating: 4.6,
  },
  {
    name: "Puma Tazon Modern",
    category: "Training",
    price: 5999,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma Retaliate 3",
    category: "Training",
    price: 4999,
    discount: 35,
    rating: 4.4,
  },
  {
    name: "Puma Cell Vive",
    category: "Training",
    price: 5499,
    discount: 30,
    rating: 4.4,
  },
  {
    name: "Puma Disperse XT 4",
    category: "Training",
    price: 5799,
    discount: 28,
    rating: 4.5,
  },
  {
    name: "Puma Better Foam Pro",
    category: "Training",
    price: 6999,
    discount: 22,
    rating: 4.6,
  },
  {
    name: "Puma Flex Essential",
    category: "Training",
    price: 3999,
    discount: 40,
    rating: 4.3,
  },

  {
    name: "Puma Ultra Ultimate FG",
    category: "Football",
    price: 15999,
    discount: 10,
    rating: 4.9,
  },
  {
    name: "Puma Future 8 Ultimate",
    category: "Football",
    price: 14999,
    discount: 12,
    rating: 4.9,
  },
  {
    name: "Puma King Ultimate",
    category: "Football",
    price: 13999,
    discount: 15,
    rating: 4.8,
  },
  {
    name: "Puma Ultra Match",
    category: "Football",
    price: 9999,
    discount: 20,
    rating: 4.7,
  },
  {
    name: "Puma Future Match",
    category: "Football",
    price: 9499,
    discount: 22,
    rating: 4.7,
  },
  {
    name: "Puma King Match",
    category: "Football",
    price: 8999,
    discount: 25,
    rating: 4.6,
  },
  {
    name: "Puma Ultra Play",
    category: "Football",
    price: 5999,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma Future Play",
    category: "Football",
    price: 5499,
    discount: 35,
    rating: 4.4,
  },

  {
    name: "Puma MB.04 LaMelo Ball",
    category: "Basketball",
    price: 13999,
    discount: 10,
    rating: 4.9,
  },
  {
    name: "Puma All-Pro Nitro",
    category: "Basketball",
    price: 12999,
    discount: 15,
    rating: 4.8,
  },
  {
    name: "Puma Rise Nitro",
    category: "Basketball",
    price: 10999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma Court Rider Chaos",
    category: "Basketball",
    price: 9999,
    discount: 20,
    rating: 4.7,
  },
  {
    name: "Puma Triple Basketball",
    category: "Basketball",
    price: 7999,
    discount: 25,
    rating: 4.6,
  },
  {
    name: "Puma Rebound Future",
    category: "Basketball",
    price: 6999,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma Playmaker Pro",
    category: "Basketball",
    price: 8499,
    discount: 22,
    rating: 4.6,
  },
  {
    name: "Puma Ferrari Drift Cat Decima",
    category: "Motorsport",
    price: 8999,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma Ferrari Neo Cat",
    category: "Motorsport",
    price: 7999,
    discount: 25,
    rating: 4.7,
  },
  {
    name: "Puma Ferrari Roma",
    category: "Motorsport",
    price: 9999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma BMW M Motorsport Drift Cat",
    category: "Motorsport",
    price: 8499,
    discount: 22,
    rating: 4.7,
  },
  {
    name: "Puma BMW M Motorsport X-Ray",
    category: "Motorsport",
    price: 9499,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma Mercedes-AMG Petronas Tiburion",
    category: "Motorsport",
    price: 10999,
    discount: 15,
    rating: 4.9,
  },
  {
    name: "Puma Mercedes-AMG Petronas Neo Cat",
    category: "Motorsport",
    price: 8999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma Red Bull Racing Drift Cat",
    category: "Motorsport",
    price: 9999,
    discount: 15,
    rating: 4.8,
  },

  {
    name: "Puma Essentials Logo Tee Black",
    category: "T-Shirts",
    price: 1499,
    discount: 35,
    rating: 4.5,
  },
  {
    name: "Puma Essentials Logo Tee White",
    category: "T-Shirts",
    price: 1499,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma Active Small Logo Tee",
    category: "T-Shirts",
    price: 1799,
    discount: 30,
    rating: 4.4,
  },
  {
    name: "Puma Graphic Logo Tee",
    category: "T-Shirts",
    price: 1999,
    discount: 25,
    rating: 4.5,
  },
  {
    name: "Puma Performance DryCELL Tee",
    category: "T-Shirts",
    price: 2499,
    discount: 20,
    rating: 4.6,
  },
  {
    name: "Puma Train Favorite Tee",
    category: "T-Shirts",
    price: 2299,
    discount: 25,
    rating: 4.6,
  },
  {
    name: "Puma Run Favorite Tee",
    category: "T-Shirts",
    price: 2499,
    discount: 20,
    rating: 4.7,
  },
  {
    name: "Puma TeamLIGA Jersey",
    category: "T-Shirts",
    price: 2799,
    discount: 18,
    rating: 4.7,
  },
  {
    name: "Puma BMW Motorsport Tee",
    category: "T-Shirts",
    price: 3499,
    discount: 15,
    rating: 4.8,
  },
  {
    name: "Puma Ferrari Race Tee",
    category: "T-Shirts",
    price: 3799,
    discount: 12,
    rating: 4.8,
  },

  {
    name: "Puma Essentials Track Pants",
    category: "Track Pants",
    price: 2999,
    discount: 30,
    rating: 4.6,
  },
  {
    name: "Puma Active Woven Pants",
    category: "Track Pants",
    price: 3299,
    discount: 25,
    rating: 4.6,
  },
  {
    name: "Puma Run Favorite Pants",
    category: "Track Pants",
    price: 3999,
    discount: 20,
    rating: 4.7,
  },
  {
    name: "Puma Training Knit Pants",
    category: "Track Pants",
    price: 3599,
    discount: 22,
    rating: 4.6,
  },
  {
    name: "Puma BMW Motorsport Pants",
    category: "Track Pants",
    price: 4999,
    discount: 15,
    rating: 4.8,
  },
  {
    name: "Puma Essentials Hoodie Black",
    category: "Hoodies",
    price: 3999,
    discount: 25,
    rating: 4.7,
  },
  {
    name: "Puma Essentials Hoodie Grey",
    category: "Hoodies",
    price: 3999,
    discount: 20,
    rating: 4.7,
  },
  {
    name: "Puma Power Colorblock Hoodie",
    category: "Hoodies",
    price: 4499,
    discount: 22,
    rating: 4.8,
  },
  {
    name: "Puma BMW Motorsport Hoodie",
    category: "Hoodies",
    price: 5999,
    discount: 15,
    rating: 4.9,
  },
  {
    name: "Puma Ferrari Race Hoodie",
    category: "Hoodies",
    price: 6499,
    discount: 12,
    rating: 4.9,
  },

  {
    name: "Puma Phase Backpack",
    category: "Bags",
    price: 1999,
    discount: 30,
    rating: 4.6,
  },
  {
    name: "Puma Deck Backpack",
    category: "Bags",
    price: 2499,
    discount: 25,
    rating: 4.7,
  },
  {
    name: "Puma Challenger Duffel Bag",
    category: "Bags",
    price: 3499,
    discount: 20,
    rating: 4.8,
  },

  {
    name: "Puma Baseball Cap",
    category: "Accessories",
    price: 999,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma Training Cap",
    category: "Accessories",
    price: 1199,
    discount: 25,
    rating: 4.6,
  },

  {
    name: "Puma Suede Classic XXI",
    category: "Lifestyle",
    price: 7999,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma Suede XL",
    category: "Lifestyle",
    price: 8999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma Easy Rider Mix",
    category: "Lifestyle",
    price: 8499,
    discount: 22,
    rating: 4.7,
  },
  {
    name: "Puma Future Rider Play On",
    category: "Lifestyle",
    price: 7499,
    discount: 25,
    rating: 4.7,
  },
  {
    name: "Puma Roma Classic",
    category: "Lifestyle",
    price: 6999,
    discount: 28,
    rating: 4.6,
  },
  {
    name: "Puma Graviton Pro",
    category: "Lifestyle",
    price: 6499,
    discount: 30,
    rating: 4.5,
  },
  {
    name: "Puma X-Ray Speed",
    category: "Lifestyle",
    price: 6999,
    discount: 25,
    rating: 4.6,
  },

  {
    name: "Puma Velocity Nitro 2",
    category: "Running",
    price: 10999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma Velocity Nitro Women's",
    category: "Running",
    price: 9999,
    discount: 22,
    rating: 4.7,
  },
  {
    name: "Puma Deviate Nitro Elite",
    category: "Running",
    price: 15999,
    discount: 10,
    rating: 4.9,
  },
  {
    name: "Puma ForeverRun Women's",
    category: "Running",
    price: 12999,
    discount: 15,
    rating: 4.8,
  },
  {
    name: "Puma Electrify Nitro 3",
    category: "Running",
    price: 7999,
    discount: 30,
    rating: 4.6,
  },

  {
    name: "Puma Palermo OG",
    category: "Sneakers",
    price: 8999,
    discount: 20,
    rating: 4.8,
  },
  {
    name: "Puma RS-X Reinvention",
    category: "Sneakers",
    price: 10999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma CA Pro Lux III",
    category: "Sneakers",
    price: 9499,
    discount: 20,
    rating: 4.7,
  },
  {
    name: "Puma Scuderia Ferrari Backpack",
    category: "Bags",
    price: 3999,
    discount: 18,
    rating: 4.8,
  },
  {
    name: "Puma Essentials Sports Cap",
    category: "Accessories",
    price: 1299,
    discount: 20,
    rating: 4.7,
  },

];
const importData = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    await Product.deleteMany();

    await Product.insertMany(products);

    console.log("Products Inserted");

    process.exit();
  } catch (error) {
    console.log(error);

    process.exit(1);
  }
};

importData();